services:
    gift-ai:
        build: 
            context: .
        container_name: gift-ai-container
        ports:
        - "80:80"
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "localhost/index.html"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
